DATA_FOLDER_NAME = '../data/giraffe_9/'

TEMP_FOLDER_NAME = '../temp/'

SEG_THRESHOLD = 10

DEBUG = True

BORDER_STEP = 12

NON_PIECE_VAL = -1

STRAIGHT_SEG_ANGLE_CUTOFF = 170

STRAIGHT_SEG_LEN_CUTOFF = 10

SAME_EDGE_ANGLE_CUTOFF = 45

EDGE_STICK_OUT_DIST_CUTOFF = 15

EDGE_STICK_OUT_SCORE_CUTOFF = 500